version: 1.0.{build}-{branch}

cache:
  - node_modules

environment:
  matrix:
    - NOV: 4
    - NOV: 5
    - NOV: 6

platform:
  - x64
  - x86

install:
  - ps: Install-Product node $env:NOV $env:PLATFORM
  - npm install

build: off

before_test:
  - openssl version
  - node -v
  - npm -v

test_script:
  - npm test

after_test:
  - npm pack
  - cd top
  - npm pack
  - copy /b *.tgz ..
  - cd ..
  - 7z a root.zip .\pem\*

artifacts:
  - path: root.zip
    name: Root certificates
    type: zip
  - path: .\*.tgz
    name: NPM package(s)
