version: 1.0.{build}-{branch}

cache:
  - node_modules

environment:
  matrix:
    - NOV: 10
    - NOV: 9
    - NOV: 8
    - NOV: 6

  NOV_LTS: 8

platform:
  - x64
  - x86

install:
  - ps: Install-Product node $env:NOV_LTS x64
  - npm install
  - cd n-api
  - npm install
  - ps: $arch = node -p process.arch
  - ps: Copy-Item .\build\Release\crypt32.node -Destination ..\lib\crypt32-$arch.node
  - ps: Install-Product node $env:NOV_LTS x86
  - npm install
  - ps: $arch = node -p process.arch
  - ps: Copy-Item .\build\Release\crypt32.node -Destination ..\lib\crypt32-$arch.node
  - cd ..
  - ps: Install-Product node $env:NOV $env:PLATFORM

build: off

before_test:
  - openssl version
  - node -v
  - npm -v

test_script:
  # - npm test

after_test:
  - npm pack
  # - 7z a root.zip .\pem\*

artifacts:
  - path: root.zip
    name: Root certificates
    type: zip
  - path: .\*.tgz
    name: NPM package(s)
